version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root-pw
      POSTGRES_DB: reporting
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
